debug

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -12,7 +12,18 @@ services:
         condition: service_completed_successfully
       redis:
         condition: service_started
-    entrypoint: ["opentelemetry-instrument", "--logs_exporter", "otlp", "--traces_exporter", "none", "--metrics_exporter", "otlp", "--service_name", "control_node", "python", "-u", "/app/validator/control_node/src/main.py"]
+    #entrypoint: ["opentelemetry-instrument", "--logs_exporter", "otlp", "--traces_exporter", "none", "--metrics_exporter", "otlp", "--service_name", "control_node", "python", "-u", "/app/validator/control_node/src/main.py"]
+    entrypoint: >
+      sh -c "
+        echo 'Python path:' &&
+        python -c 'import sys; print("\n".join(sys.path))' &&
+        echo '\nExecutable path:' &&
+        echo $PATH &&
+        echo '\nPython packages:' &&
+        pip list &&
+        which opentelemetry-instrument || echo 'opentelemetry-instrument not found' &&
+        python -c 'from opentelemetry.instrumentation.auto_instrumentation import AutoInstrumentation; print(AutoInstrumentation)'
+      "
     volumes:
       - ${HOME}/.bittensor/wallets:/root/.bittensor/wallets
     env_file:
